[package]
name = "alloc_system"
version = "0.0.0"
authors = ["The Rust Project Developers"]

[lib]
name = "alloc_system"
crate-type = ["rlib"]

[target.aarch64-none-elf.dependencies.libnx-rs]
git = "https://github.com/ischeinkman/libnx-rs"
